apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: edka
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/edkadigital/charts
  type: "oci"
  secretRef:
    name: docker-registry-github
---